version: '3.7'
services:
  redis:
    image: redis:alpine
    ports:
      - '6379'
    networks:
      - motoblog

  gatekeeper:
    depends_on:
      - redis
    image: docker.pkg.github.com/oslokommune/gatekeeper/gatekeeper:0.0.10
    networks:
      - motoblog
    ports:
      - "4554:4554"
    environment:
      DISCOVERY_URL: ${GATEKEEPER_DISCOVERY_URL}
      CLIENT_ID: ${GATEKEEPER_CLIENT_ID}
      CLIENT_SECRET: ${GATEKEEPER_CLIENT_SECRET}
      BASE_URL: http://localhost:4554
      REDIS_URI: redis://redis:6379
      UPSTREAMS: "post-service=http://post_service:3000"
      CORS_ORIGINS: "http://localhost:8080"
      SUCCESSFUL_LOGIN_ORIGIN: "http://localhost:8080"
      SUCCESSFUL_LOGOUT_ORIGIN: "http://localhost:8080"
      ERROR_URL: "http://localhost:8080/error"

  post_service:
    depends_on:
      - redis
    image: docker.pkg.github.com/tuuturu/post_service:latest
    ports:
      - '3000'
    networks:
      - motoblog
    environment:
      GATEKEEPER_URL: http://gatekeeper:4554
      LOG_LEVEL: info
      REDIS_URL: redis://redis:6379

networks:
  motoblog:
