version: '3.7'
services:
  redis:
    image: redis:alpine
    ports:
      - '6379'
    networks:
      - motoblog

  gatekeeper:
    depends_on:
      - redis
    image: docker.pkg.github.com/oslokommune/gatekeeper/gatekeeper:0.0.17
    networks:
      - motoblog
    ports:
      - "4554:4554"
    environment:
      NODE_ENV: development
      BASE_URL: http://localhost:4554
      CLIENT_ID: ${GATEKEEPER_CLIENT_ID}
      CLIENT_SECRET: ${GATEKEEPER_CLIENT_SECRET}
      DISCOVERY_URL: ${GATEKEEPER_DISCOVERY_URL}
      ERROR_URL: "http://localhost:8080/error"
      LOG_LEVEL: debug
      LOG_PRETTY_PRINT: 'true'
      ORIGIN_WHITELIST: "http://localhost:8080"
      REDIS_URI: redis://redis:6379
      UPSTREAMS: "post-service=http://post_service:3000"

  post_service:
    depends_on:
      - redis
    image: docker.pkg.github.com/tuuturu/post_service:0.0.6
    ports:
      - '3000'
    networks:
      - motoblog
    environment:
      GATEKEEPER_URL: http://gatekeeper:4554
      LOG_LEVEL: info
      REDIS_URL: redis://redis:6379

networks:
  motoblog:
